FROM golang:1.22 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o app .

FROM gcr.io/distroless/base
WORKDIR /app
COPY --from=builder /app/app .
CMD ["./app"] 